GET https://nickson.zendesk.com/api/v2/tickets.json
Authorization: Basic bmlja3Nvbm5lckBnbWFpbC5jb206WkRlcmdvc3VtNyM=

###

GET https://nickson.zendesk.com/api/v2/job_statuses/tickets.json
Authorization: Basic bmlja3Nvbm5lckBnbWFpbC5jb206WkRlcmdvc3VtNyM=

###

GET https://nickson.zendesk.com/api/v2/job_statuses.json
Authorization: Basic bmlja3Nvbm5lckBnbWFpbC5jb206WkRlcmdvc3VtNyM=

###

GET https://nickson.zendesk.com/api/v2/requests.json
Authorization: Basic bmlja3Nvbm5lckBnbWFpbC5jb206WkRlcmdvc3VtNyM=